age = input('How old are you? ')
print (f'In 10 yeards, you will be {int(age) + 10} years old.')
print (f'In 20 yeards, you will be {int(age) + 20} years old.')
print (f'In 30 yeards, you will be {int(age) + 30} years old.')
print (f'In 40 yeards, you will be {int(age) + 40} years old.')
